In [61]:
import numpy as np

def mmultiply(first, second):
    output = []
    trans_s = np.transpose(second)
    for row in first:
        layer = []
        for col in trans_s:
            element = sum(list(map(lambda x: x[0] * x[1], zip(row, col))))
            layer.append(element)
        output = np.append(output, layer, axis=0)
    return output

In [62]:
A = np.array([[2,0],[1,3]])
V = np.array([[4],[5]])
mmultiply(A, V)

array([ 8., 19.])

In [63]:
np.dot(A, V)

array([[ 8],
       [19]])

In [64]:
np.multiply(A,V)

array([[ 8,  0],
       [ 5, 15]])

In [65]:
np.transpose(V)

array([[4, 5]])

In [66]:
mmultiply(V, A)

array([ 8.,  0., 10.,  0.])