In [2]:
import numpy as np

v = np.array([5,2,1])

print(v)
print(v.shape)

[5 2 1]
(3,)


In [3]:
v[1]

2

In [16]:
m = np.array([[5,2,1],[2,0,1]])

print(m)
print(m.shape)
print(m.size)

[[5 2 1]
 [2 0 1]]
(2, 3)
6


In [17]:
m[0]

array([5, 2, 1])

In [18]:
m[0][1]

2

In [19]:
m_t = np.transpose(m)
print(m_t)
print(m_t.shape)

[[5 2]
 [2 0]
 [1 1]]
(3, 2)


In [20]:
print(m.reshape(3,2))
print('---')
print(m.reshape(3,1,2))
print('---')
print(m.reshape(-1,1,2))

[[5 2]
 [1 2]
 [0 1]]
---
[[[5 2]]

 [[1 2]]

 [[0 1]]]
---
[[[5 2]]

 [[1 2]]

 [[0 1]]]


In [24]:
t = np.array([[[1., 2.,3.], [4.,5.,6.]], [[7.,8.,9.], [11.,12.,13.]]])

print(t)
print('---')
# The first element of shape shows how many, and the second and third elements shows the dimension
print(t.shape)
print('---')
print(t[0])
print('---')
print(t[1])
print('---')
# print(t[2])
# print('---')
print(t.size)
print('---')
print(t.reshape(3,2,-1))
print('---')
print(t.reshape(3,-1,1))

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [11. 12. 13.]]]
---
(2, 2, 3)
---
[[1. 2. 3.]
 [4. 5. 6.]]
---
[[ 7.  8.  9.]
 [11. 12. 13.]]
---
12
---
[[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 11.]
  [12. 13.]]]
---
[[[ 1.]
  [ 2.]
  [ 3.]
  [ 4.]]

 [[ 5.]
  [ 6.]
  [ 7.]
  [ 8.]]

 [[ 9.]
  [11.]
  [12.]
  [13.]]]


In [25]:
v = np.zeros((2, 3, 5, 5))

print(v)

[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]]


In [26]:
a = np.array([[4, 2, 3],[2, 0, 1]])

b = np.transpose(a)

c = np.dot(a,b)

print(c)

[[29 11]
 [11  5]]


In [27]:
pinv_a = np.linalg.pinv(a)

print(pinv_a)
print(np.dot(a, pinv_a))
print(np.dot(pinv_a, a))

[[-0.08333333  0.58333333]
 [ 0.41666667 -0.91666667]
 [ 0.16666667 -0.16666667]]
[[ 1.00000000e+00  7.77156117e-16]
 [-2.77555756e-17  1.00000000e+00]]
[[ 0.83333333 -0.16666667  0.33333333]
 [-0.16666667  0.83333333  0.33333333]
 [ 0.33333333  0.33333333  0.33333333]]


In [28]:
a = np.array([[1, 2],[3, 4]])
b = np.array([[5, 6],[7, 8]])
print(np.multiply(a,b))
print(np.multiply(b,a))
print(a*b)
print(b*a)

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]


In [32]:
td = np.array([[['X','X','X'],['.','.','X'],['X','X','X'],['.','.','X'],['X','X','X']],[['X','X','.'],['X','.','X'],['X','.','X'],['X','.','X'],['X','X','.']]])
print(td)

[[['X' 'X' 'X']
  ['.' '.' 'X']
  ['X' 'X' 'X']
  ['.' '.' 'X']
  ['X' 'X' 'X']]

 [['X' 'X' '.']
  ['X' '.' 'X']
  ['X' '.' 'X']
  ['X' '.' 'X']
  ['X' 'X' '.']]]


In [33]:
v = np.zeros((2, 2, 3, 5, 5))
print(v)
print(v[0][0].shape)
print(v[0][1].shape)
print(v[1][0].shape)
print(v[1][1].shape)

[[[[[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]]


  [[[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]]]



 [[[[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]]


  [[[0. 0. 0. 0. 0.]
    [0. 